services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.saas
    container_name: django_saas
    working_dir: /app/saas
    command: poetry run python manage.py runserver 0.0.0.0:8000
    ports:
      - "8088:8000"
    env_file: .env
    environment:
      - PYTHONPATH=/app/saas
    volumes:
      - ./saas:/app/saas
      - ./pyproject.toml:/app/pyproject.toml:ro
      - ./poetry.lock:/app/poetry.lock:ro
    depends_on:
      - postgres
    networks:
      - netsaas

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: bot_saas
    working_dir: /app
    command: poetry run python -m bot.main
    restart: unless-stopped
    env_file: .env
    environment:
      - PYTHONPATH=/app/bot
    volumes:
      - ./bot:/app/bot
      - ./pyproject.toml:/app/pyproject.toml:ro
      - ./poetry.lock:/app/poetry.lock:ro
    depends_on:
      - django
      - postgres
    networks:
      - netsaas

  postgres:
    image: postgres:16
    container_name: mysaasmp-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: mysaas
    ports:
      - "5438:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - netsaas

volumes:
  pgdata:

networks:
  netsaas:
